root: /home/likai/data2/AV-Project
gpus: [0,1,2,3,4,5,6,7]
data:
  train_dir: /home/likai/data2/AV-Project/Data/lrs3_data_online/tr.json
  val_dir: /home/likai/data2/AV-Project/Data/lrs3_data_online/cv.json
  test_dir: /home/likai/data2/AV-Project/Data/lrs3_data_online/tt.json
  n_src: 2
  task: sep_clean
  sample_rate: 8000
  segment: 4.0

training:
  epochs: 130
  batch_size: 4
  num_workers: 32
  half_lr: yes
  early_stop: 10
  clip_norm: 5
  exp_name: Wujian-Model-Baseline

# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5

AV_model:
  # audio conf
  N: 256
  L: 40
  B: 256
  H: 512
  P: 3
  X: 8
  # video conf
  E: 256
  V: 256
  K: 3
  D: 5
  # fusion index
  F: 256 # 等于B，Sc
  # other
  R: 4
  audio_index: 1
  norm: gln
  causal: false

video_model:
  in_channels: 1
  out_channels: 64
  video_channels: 256
  resnet_dim: 256
  kernel_size: 3
  repeat: 5

scheduler:
  min_lr: !!float 1e-8
  patience: 4
  factor: 0.5

video_checkpoint:
  path: /home/likai/data2/AV-Project/model/Wujian_Model/video_resnet18.pt

log:
  path: /home/likai/data2/AV-Project/logger
  name: AV-Project